### ISSUE TITLE
Static Datasource does not work in public dashboards

### ISSUE THREAD

**Issue by InvincibleRMC** [VolkovLabs/business-input#80]
It would be nice if it worked in public dashboards.

**Comment by mikhail-vl** [comment]
@InvincibleRMC Public dashboards supports only backend data sources. Business Input is frontend and we have no plans at the moment to implement it as backend: https://grafana.com/docs/grafana/next/dashboards/dashboard-public/#supported-data-sources.

  If you are looking to share public dashboard, check out the Infinity data source.
