### ISSUE TITLE
Broken in Grafana v11.3

### ISSUE THREAD

**Issue by Salzi** [VolkovLabs/business-input#94]
I just updated my Grafana setup to v11.3.0+security-01 and the static data source is broken. I'm using it in the variables:

## Grafana v11.2.3

![image](https://github.com/user-attachments/assets/c802d550-5ba6-46b7-b94a-663af05a8a6c)

## Grafana  v11.3.0+security-01

![image](https://github.com/user-attachments/assets/64fcfc18-83b9-4fc1-b2ff-09b5e62da34c)

As you can see there are no values anymore.

**Comment by mikhail-vl** [comment]
@Salzi Do you use the latest version 4.3.0 of the Business Input (Static data source) ?

  I tested behavior on v11.3.0+security-01, `main` branch and can't reproduce the issue.

**Comment by Salzi** [comment]
@mikhail-vl Thank you for your response—you were absolutely right. The plugin just needed an update to the latest version. I’m fairly new to Grafana and hadn’t realized that plugins require separate updates. I appreciate your help, and apologies for the oversight!

**Comment by mikhail-vl** [comment]
@Salzi We keep our plugins up to date with the latest Grafana updates.

  In the latest Grafana 11.3, you can see which plugins needs to be updated in a separate tab.
  Let us know if there is anything else.
